name: Deploy DevOps Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true

      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://your-netlify-site.netlify.app
          uploadArtifacts: true

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        if: github.ref == 'refs/heads/main'
        with:
          publish-dir: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
