name: Deploy DevOps Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://devopsprojectautomation.netlify.app/
          uploadArtifacts: false

      - name: Upload Lighthouse Results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse_results
          path: ./.lighthouseci

      - name: Install dependencies
        working-directory: devops-dashboard-react
        run: npm install

      - name: Build site
        working-directory: devops-dashboard-react
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        if: github.ref == 'refs/heads/main'
        with:
          publish-dir: devops-dashboard-react/dist
          functions-dir: devops-dashboard-react/netlify/functions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
